language: cpp

matrix:
  include:
    #
    # GCC
    #

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="TOOLSET=toolset=gcc-7"

    #
    # Clang
    #

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="TOOLSET=toolset=clang-3.6"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="TOOLSET=toolset=clang-5.0"

    - os: osx
      osx_image: xcode8.3
#      env:
#        - MATRIX_EVAL="TOOLSET=toolset=gcc-4.9"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && TOOLSET=toolset=gcc-5"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc6 && TOOLSET=toolset=gcc-6"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && TOOLSET=toolset=gcc-7"

    - os: windows
#      env:
#        - MATRIX_EVAL="TOOLSET=toolset="
        
before_install:
    - eval "${MATRIX_EVAL}"

script: 
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./quickbuild.sh --abbreviate-paths -j2 pwiz $TOOLSET; else ./quickbuild.bat --abbreviate-paths -j2 pwiz_tools/commandline $TOOLSET; fi    

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b964b972d7ac96afd45c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
