//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Model.AuditLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditLogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditLogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Model.AuditLog.AuditLogStrings", typeof(AuditLogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear audit log.
        /// </summary>
        public static string AuditLogForm__clearLogButton_Click_Clear_audit_log {
            get {
                return ResourceManager.GetString("AuditLogForm__clearLogButton_Click_Clear_audit_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Info.
        /// </summary>
        public static string AuditLogForm_AuditLogForm_All_Info {
            get {
                return ResourceManager.GetString("AuditLogForm_AuditLogForm_All_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string AuditLogForm_AuditLogForm_Clear_log {
            get {
                return ResourceManager.GetString("AuditLogForm_AuditLogForm_Clear_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable audit logging.
        /// </summary>
        public static string AuditLogForm_AuditLogForm_Enable_audit_logging {
            get {
                return ResourceManager.GetString("AuditLogForm_AuditLogForm_Enable_audit_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string AuditLogForm_AuditLogForm_Summary {
            get {
                return ResourceManager.GetString("AuditLogForm_AuditLogForm_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Redo.
        /// </summary>
        public static string AuditLogForm_AuditLogForm_Undo_Redo {
            get {
                return ResourceManager.GetString("AuditLogForm_AuditLogForm_Undo_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log.
        /// </summary>
        public static string AuditLogForm_GetViewInfo_Audit_Log {
            get {
                return ResourceManager.GetString("AuditLogForm_GetViewInfo_Audit_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Format.
        /// </summary>
        public static string AuditLogForm_GetViewInfo_Document_Format {
            get {
                return ResourceManager.GetString("AuditLogForm_GetViewInfo_Document_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string AuditLogForm_GetViewInfo_Reason {
            get {
                return ResourceManager.GetString("AuditLogForm_GetViewInfo_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string AuditLogForm_GetViewInfo_Text {
            get {
                return ResourceManager.GetString("AuditLogForm_GetViewInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string AuditLogForm_GetViewInfo_Time {
            get {
                return ResourceManager.GetString("AuditLogForm_GetViewInfo_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string ElementTypeSeparator {
            get {
                return ResourceManager.GetString("ElementTypeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} was added.
        /// </summary>
        public static string LogMessage_ToString__0____1__was_added {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0____1__was_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} was removed.
        /// </summary>
        public static string LogMessage_ToString__0____1__was_removed {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0____1__was_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed.
        /// </summary>
        public static string LogMessage_ToString__0__changed {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed to {1}.
        /// </summary>
        public static string LogMessage_ToString__0__changed_to__1_ {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__changed_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was added.
        /// </summary>
        public static string LogMessage_ToString__0__was_added {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__was_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} was added.
        /// </summary>
        public static string LogMessage_ToString__0__was_added_to__1_ {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__was_added_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was removed.
        /// </summary>
        public static string LogMessage_ToString__0__was_removed {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__was_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} was removed from.
        /// </summary>
        public static string LogMessage_ToString__0__was_removed_from__1_ {
            get {
                return ResourceManager.GetString("LogMessage_ToString__0__was_removed_from__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &gt; .
        /// </summary>
        public static string PropertySeparator {
            get {
                return ResourceManager.GetString("PropertySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- .
        /// </summary>
        public static string TabSeparator {
            get {
                return ResourceManager.GetString("TabSeparator", resourceCulture);
            }
        }
    }
}
