//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Model.AuditLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Model.AuditLog.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition method.
        /// </summary>
        public static string AcquisitionMethod {
            get {
                return ResourceManager.GetString("AcquisitionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate operation.
        /// </summary>
        public static string AggregateOperation {
            get {
                return ResourceManager.GetString("AggregateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string AnnotationDefs {
            get {
                return ResourceManager.GetString("AnnotationDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies To.
        /// </summary>
        public static string AnnotationTargets {
            get {
                return ResourceManager.GetString("AnnotationTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment percentage.
        /// </summary>
        public static string AtomPercentEnrichment {
            get {
                return ResourceManager.GetString("AtomPercentEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-select all matching transitions.
        /// </summary>
        public static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average m/z.
        /// </summary>
        public static string AverageMassMz {
            get {
                return ResourceManager.GetString("AverageMassMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to compare against.
        /// </summary>
        public static string CaseValue {
            get {
                return ResourceManager.GetString("CaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE Range.
        /// </summary>
        public static string CERange {
            get {
                return ResourceManager.GetString("CERange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision energy.
        /// </summary>
        public static string CollisionEnergy {
            get {
                return ResourceManager.GetString("CollisionEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting rows.
        /// </summary>
        public static string ColorRows {
            get {
                return ResourceManager.GetString("ColorRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column headers.
        /// </summary>
        public static string ColumnHeaders {
            get {
                return ResourceManager.GetString("ColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation voltage.
        /// </summary>
        public static string CompensationVoltage {
            get {
                return ResourceManager.GetString("CompensationVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence level.
        /// </summary>
        public static string ConfidenceLevelTimes100 {
            get {
                return ResourceManager.GetString("ConfidenceLevelTimes100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control group annotation.
        /// </summary>
        public static string ControlAnnotation {
            get {
                return ResourceManager.GetString("ControlAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control group value.
        /// </summary>
        public static string ControlValue {
            get {
                return ResourceManager.GetString("ControlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regression parameters.
        /// </summary>
        public static string Conversions {
            get {
                return ResourceManager.GetString("Conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization library path.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Settings.
        /// </summary>
        public static string DataSettings {
            get {
                return ResourceManager.GetString("DataSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declustering potential.
        /// </summary>
        public static string DeclusteringPotential {
            get {
                return ResourceManager.GetString("DeclusteringPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digestion.
        /// </summary>
        public static string DigestSettings {
            get {
                return ResourceManager.GetString("DigestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End margin.
        /// </summary>
        public static string EndMargin {
            get {
                return ResourceManager.GetString("EndMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable isotope labeling atoms.
        /// </summary>
        public static string Enrichments {
            get {
                return ResourceManager.GetString("Enrichments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DIA precursor window for exlucison.
        /// </summary>
        public static string ExclusionUseDIAWindow {
            get {
                return ResourceManager.GetString("ExclusionUseDIAWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment amino acids.
        /// </summary>
        public static string Fragment {
            get {
                return ResourceManager.GetString("Fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ion mass.
        /// </summary>
        public static string FragmentMassType {
            get {
                return ResourceManager.GetString("FragmentMassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ion selection start.
        /// </summary>
        public static string FragmentRangeFirstName {
            get {
                return ResourceManager.GetString("FragmentRangeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ion selection end.
        /// </summary>
        public static string FragmentRangeLastName {
            get {
                return ResourceManager.GetString("FragmentRangeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Scan.
        /// </summary>
        public static string FullScan {
            get {
                return ResourceManager.GetString("FullScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Comparisons.
        /// </summary>
        public static string GroupComparisonDefs {
            get {
                return ResourceManager.GetString("GroupComparisonDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Annotation (for technical replicates).
        /// </summary>
        public static string IdentityAnnotation {
            get {
                return ResourceManager.GetString("IdentityAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept.
        /// </summary>
        public static string Intercept {
            get {
                return ResourceManager.GetString("Intercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string InvariantOperandText {
            get {
                return ResourceManager.GetString("InvariantOperandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ions.
        /// </summary>
        public static string IonCount {
            get {
                return ResourceManager.GetString("IonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion match tolerance.
        /// </summary>
        public static string IonMatchTolerance {
            get {
                return ResourceManager.GetString("IonMatchTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom product ion.
        /// </summary>
        public static string IsCustom {
            get {
                return ResourceManager.GetString("IsCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic min product m/z.
        /// </summary>
        public static string IsDynamicMin {
            get {
                return ResourceManager.GetString("IsDynamicMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense fragment.
        /// </summary>
        public static string IsFragment {
            get {
                return ResourceManager.GetString("IsFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation scheme.
        /// </summary>
        public static string IsolationScheme {
            get {
                return ResourceManager.GetString("IsolationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation width.
        /// </summary>
        public static string IsolationWidth {
            get {
                return ResourceManager.GetString("IsolationWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isotope labeling enrichment.
        /// </summary>
        public static string IsotopeEnrichments {
            get {
                return ResourceManager.GetString("IsotopeEnrichments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atom.
        /// </summary>
        public static string IsotopeSymbol {
            get {
                return ResourceManager.GetString("IsotopeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled.
        /// </summary>
        public static string Labeled {
            get {
                return ResourceManager.GetString("Labeled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        public static string Layouts {
            get {
                return ResourceManager.GetString("Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass accuracy.
        /// </summary>
        public static string MassAccuracy {
            get {
                return ResourceManager.GetString("MassAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum CoV.
        /// </summary>
        public static string MaxCov {
            get {
                return ResourceManager.GetString("MaxCov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware inclusion limit.
        /// </summary>
        public static string MaxInclusions {
            get {
                return ResourceManager.GetString("MaxInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max missed cleavages.
        /// </summary>
        public static string MaxMissedCleavages {
            get {
                return ResourceManager.GetString("MaxMissedCleavages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max m/z.
        /// </summary>
        public static string MaxMz {
            get {
                return ResourceManager.GetString("MaxMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max time.
        /// </summary>
        public static string MaxTime {
            get {
                return ResourceManager.GetString("MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware transition limit.
        /// </summary>
        public static string MaxTransitions {
            get {
                return ResourceManager.GetString("MaxTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special ions.
        /// </summary>
        public static string MeasuredIons {
            get {
                return ResourceManager.GetString("MeasuredIons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum CoV.
        /// </summary>
        public static string MinCov {
            get {
                return ResourceManager.GetString("MinCov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min amino acids.
        /// </summary>
        public static string MinFragmentLength {
            get {
                return ResourceManager.GetString("MinFragmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum product ions.
        /// </summary>
        public static string MinIonCount {
            get {
                return ResourceManager.GetString("MinIonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min m/z.
        /// </summary>
        public static string MinMz {
            get {
                return ResourceManager.GetString("MinMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min time.
        /// </summary>
        public static string MinTime {
            get {
                return ResourceManager.GetString("MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last time modified.
        /// </summary>
        public static string ModifiedTime {
            get {
                return ResourceManager.GetString("ModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoisotopic m/z.
        /// </summary>
        public static string MonoisotopicMassMz {
            get {
                return ResourceManager.GetString("MonoisotopicMassMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method match tolerance m/z.
        /// </summary>
        public static string MzMatchTolerance {
            get {
                return ResourceManager.GetString("MzMatchTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion chemical formula.
        /// </summary>
        public static string NeutralFormula {
            get {
                return ResourceManager.GetString("NeutralFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalization method.
        /// </summary>
        public static string NormalizationMethod {
            get {
                return ResourceManager.GetString("NormalizationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization library.
        /// </summary>
        public static string OptimizedLibrary {
            get {
                return ResourceManager.GetString("OptimizedLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization method.
        /// </summary>
        public static string OptimizedMethodType {
            get {
                return ResourceManager.GetString("OptimizedMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion types.
        /// </summary>
        public static string PeptideIonTypesString {
            get {
                return ResourceManager.GetString("PeptideIonTypesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide Precursor charges.
        /// </summary>
        public static string PeptidePrecursorChargesString {
            get {
                return ResourceManager.GetString("PeptidePrecursorChargesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide Ion charges.
        /// </summary>
        public static string PeptideProductChargesString {
            get {
                return ResourceManager.GetString("PeptideProductChargesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide Settings.
        /// </summary>
        public static string PeptideSettings {
            get {
                return ResourceManager.GetString("PeptideSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide scope.
        /// </summary>
        public static string PerPeptide {
            get {
                return ResourceManager.GetString("PerPeptide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein scope.
        /// </summary>
        public static string PerProtein {
            get {
                return ResourceManager.GetString("PerProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a library spectrum is available, pick its most intense ions.
        /// </summary>
        public static string PickMostIntenseIons {
            get {
                return ResourceManager.GetString("PickMostIntenseIons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string PointSize {
            get {
                return ResourceManager.GetString("PointSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string PointSymbol {
            get {
                return ResourceManager.GetString("PointSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor filter m/z.
        /// </summary>
        public static string PrecursorFilter {
            get {
                return ResourceManager.GetString("PrecursorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks.
        /// </summary>
        public static string PrecursorIsotopeFilter {
            get {
                return ResourceManager.GetString("PrecursorIsotopeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isotope peaks included.
        /// </summary>
        public static string PrecursorIsotopes {
            get {
                return ResourceManager.GetString("PrecursorIsotopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor mass analyzer.
        /// </summary>
        public static string PrecursorMassAnalyzer {
            get {
                return ResourceManager.GetString("PrecursorMassAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor mass.
        /// </summary>
        public static string PrecursorMassType {
            get {
                return ResourceManager.GetString("PrecursorMassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor m/z exclusion window.
        /// </summary>
        public static string PrecursorMzWindow {
            get {
                return ResourceManager.GetString("PrecursorMzWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving power m/z.
        /// </summary>
        public static string PrecursorResMz {
            get {
                return ResourceManager.GetString("PrecursorResMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        public static string Prediction {
            get {
                return ResourceManager.GetString("Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prespecified isolation windows.
        /// </summary>
        public static string PrespecifiedIsolationWindows {
            get {
                return ResourceManager.GetString("PrespecifiedIsolationWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product mass analyzer.
        /// </summary>
        public static string ProductMassAnalyzer {
            get {
                return ResourceManager.GetString("ProductMassAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving power m/z.
        /// </summary>
        public static string ProductResMz {
            get {
                return ResourceManager.GetString("ProductResMz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-value cutoff.
        /// </summary>
        public static string QValueCutoff {
            get {
                return ResourceManager.GetString("QValueCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving power.
        /// </summary>
        public static string ResolvingPower {
            get {
                return ResourceManager.GetString("ResolvingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless next amino acids.
        /// </summary>
        public static string Restrict {
            get {
                return ResourceManager.GetString("Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time filter length.
        /// </summary>
        public static string RetentionTimeFilterLength {
            get {
                return ResourceManager.GetString("RetentionTimeFilterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time filter type.
        /// </summary>
        public static string RetentionTimeFilterType {
            get {
                return ResourceManager.GetString("RetentionTimeFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string Rgb {
            get {
                return ResourceManager.GetString("Rgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row headers.
        /// </summary>
        public static string RowHeaders {
            get {
                return ResourceManager.GetString("RowHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope.
        /// </summary>
        public static string Slope {
            get {
                return ResourceManager.GetString("Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small molecule Fragment adducts.
        /// </summary>
        public static string SmallMoleculeFragmentAdductsString {
            get {
                return ResourceManager.GetString("SmallMoleculeFragmentAdductsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small molecule Ion types.
        /// </summary>
        public static string SmallMoleculeIonTypesString {
            get {
                return ResourceManager.GetString("SmallMoleculeIonTypesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small molecule Precursor adducts.
        /// </summary>
        public static string SmallMoleculePrecursorAdductsString {
            get {
                return ResourceManager.GetString("SmallMoleculePrecursorAdductsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconvolution.
        /// </summary>
        public static string SpecialHandling {
            get {
                return ResourceManager.GetString("SpecialHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string StartMargin {
            get {
                return ResourceManager.GetString("StartMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step count.
        /// </summary>
        public static string StepCount {
            get {
                return ResourceManager.GetString("StepCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine tune step count.
        /// </summary>
        public static string StepCountFine {
            get {
                return ResourceManager.GetString("StepCountFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium tune step count.
        /// </summary>
        public static string StepCountMedium {
            get {
                return ResourceManager.GetString("StepCountMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rough tune step count.
        /// </summary>
        public static string StepCountRough {
            get {
                return ResourceManager.GetString("StepCountRough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size.
        /// </summary>
        public static string StepSize {
            get {
                return ResourceManager.GetString("StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary method.
        /// </summary>
        public static string SummarizationMethod {
            get {
                return ResourceManager.GetString("SummarizationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Terminus {
            get {
                return ResourceManager.GetString("Terminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Settings.
        /// </summary>
        public static string TransitionSettings {
            get {
                return ResourceManager.GetString("TransitionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use optimization values when present.
        /// </summary>
        public static string UseOptimizationValues {
            get {
                return ResourceManager.GetString("UseOptimizationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use high-selectivity extraction.
        /// </summary>
        public static string UseSelectiveExtraction {
            get {
                return ResourceManager.GetString("UseSelectiveExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use zero for missing peaks.
        /// </summary>
        public static string UseZeroForMissingPeaks {
            get {
                return ResourceManager.GetString("UseZeroForMissingPeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ViewSpecs {
            get {
                return ResourceManager.GetString("ViewSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows per scan.
        /// </summary>
        public static string WindowsPerScan {
            get {
                return ResourceManager.GetString("WindowsPerScan", resourceCulture);
            }
        }
    }
}
